author: "Juan Carlos Villase√±or-Derbez (JC)"
affiliation: "Rosenstiel School of Marine, Atmospheric, and Earth Science"

project:
  output-dir: .
  execute-dir: project

#bibliography: references.bib
format:
  revealjs:
    theme: simple
    incremental: true
    logo: https://ucomm.miami.edu/_assets/images/tools-and-resources/signatures/png/um-horizontal-rgb.png
    footer: "[EVR 662](https://jcvdav.github.io/EVR_662/)"
    code-fold: true
    preview-links: true
    echo: true
    slide-number: true
    smaller: true
    fig-align: center
